spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:showtime_db}
    username: ${POSTGRES_USER:showtime_user}
    password: ${POSTGRES_PASSWORD:showtime_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect