spring:
  application:
    name: api-gateway

server:
  port: 8080

services:
  concerts:
    base-url: ${CONCERTS_BASE_URL:http://localhost:8081}
  customers:
    base-url: ${CUSTOMERS_BASE_URL:http://localhost:8082}
  showtimes:
    base-url: ${SHOWTIMES_BASE_URL:http://localhost:8083}
  reservations:
    base-url: ${RESERVATIONS_BASE_URL:http://localhost:8085}
