spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: concerts-service
              uri: http://concerts-service:8080
              predicates:
                - Path=/api/concerts/**
              filters:
                - RewritePath=/api/concerts/(?<segment>.*), /$\{segment}

            - id: customers-service
              uri: http://customers-service:8080
              predicates:
                - Path=/api/customers/**
              filters:
                - RewritePath=/api/customers/(?<segment>.*), /$\{segment}

            - id: showtimes-service
              uri: http://showtimes-service:8080
              predicates:
                - Path=/api/showtimes/**
              filters:
                - RewritePath=/api/showtimes/(?<segment>.*), /$\{segment}

            - id: reservation-service
              uri: http://reservation-service:8080
              predicates:
                - Path=/api/reservations/**
              filters:
                - RewritePath=/api/reservations/(?<segment>.*), /$\{segment}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: concerts-service
        url: /api/concerts/v3/api-docs
      - name: customers-service
        url: /api/customers/v3/api-docs
      - name: showtimes-service
        url: /api/showtimes/v3/api-docs
      - name: reservation-service
        url: /api/reservations/v3/api-docs