spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: concerts-service
              uri: http://concerts-service:8080
              predicates:
                - Path=/api/concerts/**

            - id: customers-service
              uri: http://customers-service:8080
              predicates:
                - Path=/api/customers/**

            - id: showtimes-service
              uri: http://showtimes-service:8080
              predicates:
                - Path=/api/showtimes/**

            - id: reservation-service
              uri: http://reservation-service:8080
              predicates:
                - Path=/api/reservations/**

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: concerts-service
        url: http://localhost:8081/v3/api-docs
      - name: customers-service
        url: http://localhost:8082/v3/api-docs
      - name: showtimes-service
        url: http://localhost:8083/v3/api-docs
      - name: reservation-service
        url: http://localhost:8085/v3/api-docs