spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:customers_db}
    username: ${POSTGRES_USER:customer_user}
    password: ${POSTGRES_PASSWORD:customer_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect